# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\wsl_app_v2.0\gui\main\ui\wsl_analytics_ui_v2.0'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1206, 853)
        Form.setStyleSheet("\n"
"background-color: #1572A1;")
        self.tab_top_lvl = QtWidgets.QTabWidget(Form)
        self.tab_top_lvl.setGeometry(QtCore.QRect(-6, -1, 1221, 861))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(13)
        self.tab_top_lvl.setFont(font)
        self.tab_top_lvl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_top_lvl.setStyleSheet("\n"
"QTabWidget::tab-bar {\n"
"\n"
" }\n"
"\n"
" QTabBar::tab {\n"
"  background: #bae1ff;\n"
"  font-family: Bahnschrift Semibold;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: #c462fd;\n"
" }")
        self.tab_top_lvl.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_top_lvl.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_top_lvl.setIconSize(QtCore.QSize(20, 20))
        self.tab_top_lvl.setObjectName("tab_top_lvl")
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setObjectName("tab_main")
        self.tab_top_lvl.addTab(self.tab_main, "")
        self.tab_schedule = QtWidgets.QWidget()
        self.tab_schedule.setObjectName("tab_schedule")
        self.tab_top_lvl.addTab(self.tab_schedule, "")
        self.tab_heat_analysis = QtWidgets.QWidget()
        self.tab_heat_analysis.setObjectName("tab_heat_analysis")
        self.tab_top_lvl.addTab(self.tab_heat_analysis, "")
        self.tab_data_entry = QtWidgets.QWidget()
        self.tab_data_entry.setObjectName("tab_data_entry")
        self.tab_second_lvl = QtWidgets.QTabWidget(self.tab_data_entry)
        self.tab_second_lvl.setGeometry(QtCore.QRect(40, 50, 1131, 711))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(9)
        self.tab_second_lvl.setFont(font)
        self.tab_second_lvl.setAutoFillBackground(False)
        self.tab_second_lvl.setStyleSheet("background-color: rgb(148, 179, 253);\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 10px solid #red;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C4;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}")
        self.tab_second_lvl.setDocumentMode(True)
        self.tab_second_lvl.setObjectName("tab_second_lvl")
        self.tab_entry_results = QtWidgets.QWidget()
        self.tab_entry_results.setObjectName("tab_entry_results")
        self.tab_second_lvl.addTab(self.tab_entry_results, "")
        self.tab_entry_heat = QtWidgets.QWidget()
        self.tab_entry_heat.setObjectName("tab_entry_heat")
        self.tab_second_lvl.addTab(self.tab_entry_heat, "")
        self.tab_entry_break = QtWidgets.QWidget()
        self.tab_entry_break.setObjectName("tab_entry_break")
        self.groupbox_addbreak_location = QtWidgets.QGroupBox(self.tab_entry_break)
        self.groupbox_addbreak_location.setGeometry(QtCore.QRect(49, 39, 461, 291))
        self.groupbox_addbreak_location.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 75 14pt \"Verdana\";\n"
"")
        self.groupbox_addbreak_location.setObjectName("groupbox_addbreak_location")
        self.pushButton = QtWidgets.QPushButton(self.groupbox_addbreak_location)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(140, 220, 151, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(151, 50))
        self.pushButton.setStyleSheet("background-color: rgb(246, 234, 190);\n"
"font: 63 11pt \"Verdana\";")
        self.pushButton.setObjectName("pushButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupbox_addbreak_location)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 50, 371, 153))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.groupBox = QtWidgets.QGroupBox(self.tab_entry_break)
        self.groupBox.setGeometry(QtCore.QRect(590, 380, 261, 231))
        self.groupBox.setStyleSheet("background-color: rgb(185, 131, 255);\n"
"font: 75 14pt \"Verdana\";\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 57, 192, 141))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_2.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_3.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_4.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_entry_break)
        self.groupBox_2.setGeometry(QtCore.QRect(590, 40, 461, 291))
        self.groupBox_2.setStyleSheet("background-color: rgb(185, 131, 255);\n"
"font: 75 14pt \"Verdana\";\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(49, 59, 341, 191))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkBox.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.checkBox.setObjectName("checkBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkBox_2.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkBox_3.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkBox_4.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkBox_5.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkBox_6.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.checkBox_6.setObjectName("checkBox_6")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkBox_7.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.checkBox_7.setObjectName("checkBox_7")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_entry_break)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 380, 461, 231))
        self.groupBox_3.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 75 14pt \"Verdana\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(30, 50, 412, 161))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_8.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_10.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_11 = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_11.sizePolicy().hasHeightForWidth())
        self.checkBox_11.setSizePolicy(sizePolicy)
        self.checkBox_11.setMinimumSize(QtCore.QSize(75, 0))
        self.checkBox_11.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: rgb(40, 223, 153);")
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_3.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_12.sizePolicy().hasHeightForWidth())
        self.checkBox_12.setSizePolicy(sizePolicy)
        self.checkBox_12.setMinimumSize(QtCore.QSize(75, 0))
        self.checkBox_12.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: #FDFFA9;")
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_3.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_13.sizePolicy().hasHeightForWidth())
        self.checkBox_13.setSizePolicy(sizePolicy)
        self.checkBox_13.setMinimumSize(QtCore.QSize(75, 0))
        self.checkBox_13.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: rgb(216, 58, 86);")
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_3.addWidget(self.checkBox_13)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_9.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_9 = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_9.sizePolicy().hasHeightForWidth())
        self.checkBox_9.setSizePolicy(sizePolicy)
        self.checkBox_9.setMinimumSize(QtCore.QSize(75, 0))
        self.checkBox_9.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: rgb(40, 223, 153);")
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_10.sizePolicy().hasHeightForWidth())
        self.checkBox_10.setSizePolicy(sizePolicy)
        self.checkBox_10.setMinimumSize(QtCore.QSize(75, 0))
        self.checkBox_10.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: #FDFFA9;")
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout.addWidget(self.checkBox_10)
        self.checkBox_8 = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_8.sizePolicy().hasHeightForWidth())
        self.checkBox_8.setSizePolicy(sizePolicy)
        self.checkBox_8.setMinimumSize(QtCore.QSize(75, 0))
        self.checkBox_8.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: rgb(216, 58, 86);")
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout.addWidget(self.checkBox_8)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.formLayout_4.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_4.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_entry_break)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 530, 151, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(151, 50))
        self.pushButton_2.setStyleSheet("background-color: rgb(154, 223, 244);\n"
"font: 63 11pt \"Verdana\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_entry_break)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(890, 420, 151, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(151, 50))
        self.pushButton_3.setStyleSheet("background-color: rgb(154, 223, 244);\n"
"font: 63 11pt \"Verdana\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tab_second_lvl.addTab(self.tab_entry_break, "")
        self.tab_entry_surfer = QtWidgets.QWidget()
        self.tab_entry_surfer.setObjectName("tab_entry_surfer")
        self.tab_second_lvl.addTab(self.tab_entry_surfer, "")
        self.tab_top_lvl.addTab(self.tab_data_entry, "")

        self.retranslateUi(Form)
        self.tab_top_lvl.setCurrentIndex(3)
        self.tab_second_lvl.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tab_top_lvl.setTabText(self.tab_top_lvl.indexOf(self.tab_main), _translate("Form", "Main"))
        self.tab_top_lvl.setTabText(self.tab_top_lvl.indexOf(self.tab_schedule), _translate("Form", "Schedule"))
        self.tab_top_lvl.setTabText(self.tab_top_lvl.indexOf(self.tab_heat_analysis), _translate("Form", "Heat Analysis"))
        self.tab_second_lvl.setTabText(self.tab_second_lvl.indexOf(self.tab_entry_results), _translate("Form", "Heat Resuts"))
        self.tab_second_lvl.setTabText(self.tab_second_lvl.indexOf(self.tab_entry_heat), _translate("Form", "Add Heat"))
        self.groupbox_addbreak_location.setTitle(_translate("Form", "Location"))
        self.pushButton.setText(_translate("Form", "New Location"))
        self.label.setText(_translate("Form", "Continent:"))
        self.label_2.setText(_translate("Form", "Country:"))
        self.label_3.setText(_translate("Form", "Region:"))
        self.label_4.setText(_translate("Form", "Break:"))
        self.groupBox.setTitle(_translate("Form", "Surfability (%)"))
        self.label_5.setText(_translate("Form", "Clean:"))
        self.label_6.setText(_translate("Form", "Too Small:"))
        self.label_7.setText(_translate("Form", "Blown Out:"))
        self.groupBox_2.setTitle(_translate("Form", "Break Type"))
        self.checkBox.setText(_translate("Form", "Beach"))
        self.checkBox_2.setText(_translate("Form", "Point"))
        self.checkBox_3.setText(_translate("Form", "Reef"))
        self.checkBox_4.setText(_translate("Form", "River"))
        self.checkBox_5.setText(_translate("Form", "Sandbar"))
        self.checkBox_6.setText(_translate("Form", "Jetty"))
        self.checkBox_7.setText(_translate("Form", "Engineered   "))
        self.groupBox_3.setTitle(_translate("Form", "Skill Factors"))
        self.label_8.setText(_translate("Form", "Reliability:"))
        self.label_10.setText(_translate("Form", "Ability:"))
        self.checkBox_11.setText(_translate("Form", "l"))
        self.checkBox_12.setText(_translate("Form", "l"))
        self.checkBox_13.setText(_translate("Form", "l"))
        self.label_9.setText(_translate("Form", "Shoulder Burn:  "))
        self.checkBox_9.setText(_translate("Form", "l"))
        self.checkBox_10.setText(_translate("Form", "l"))
        self.checkBox_8.setText(_translate("Form", "l"))
        self.pushButton_2.setText(_translate("Form", "Submit"))
        self.pushButton_3.setText(_translate("Form", "Clear"))
        self.tab_second_lvl.setTabText(self.tab_second_lvl.indexOf(self.tab_entry_break), _translate("Form", "Add Break"))
        self.tab_second_lvl.setTabText(self.tab_second_lvl.indexOf(self.tab_entry_surfer), _translate("Form", "Add Surfer"))
        self.tab_top_lvl.setTabText(self.tab_top_lvl.indexOf(self.tab_data_entry), _translate("Form", "Data Entry"))
