# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\wsl_app_v2.0\gui\main\ui\wsl_analytics_ui_v2.0'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1206, 853)
        Form.setStyleSheet("\n"
"background-color: #1572A1;")
        self.tab_top_lvl = QtWidgets.QTabWidget(Form)
        self.tab_top_lvl.setGeometry(QtCore.QRect(-6, -1, 1221, 861))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(13)
        self.tab_top_lvl.setFont(font)
        self.tab_top_lvl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_top_lvl.setStyleSheet("\n"
"QTabWidget::tab-bar {\n"
"\n"
" }\n"
"\n"
" QTabBar::tab {\n"
"  background: #bae1ff;\n"
"  font-family: Bahnschrift Semibold;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: #c462fd;\n"
" }")
        self.tab_top_lvl.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_top_lvl.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_top_lvl.setIconSize(QtCore.QSize(20, 20))
        self.tab_top_lvl.setObjectName("tab_top_lvl")
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setObjectName("tab_main")
        self.tab_top_lvl.addTab(self.tab_main, "")
        self.tab_schedule = QtWidgets.QWidget()
        self.tab_schedule.setObjectName("tab_schedule")
        self.tab_top_lvl.addTab(self.tab_schedule, "")
        self.tab_heat_analysis = QtWidgets.QWidget()
        self.tab_heat_analysis.setObjectName("tab_heat_analysis")
        self.tab_top_lvl.addTab(self.tab_heat_analysis, "")
        self.tab_data_entry = QtWidgets.QWidget()
        self.tab_data_entry.setObjectName("tab_data_entry")
        self.tab_second_lvl = QtWidgets.QTabWidget(self.tab_data_entry)
        self.tab_second_lvl.setGeometry(QtCore.QRect(40, 50, 1131, 711))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(9)
        self.tab_second_lvl.setFont(font)
        self.tab_second_lvl.setAutoFillBackground(False)
        self.tab_second_lvl.setStyleSheet("background-color: rgb(148, 179, 253);\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 10px solid #red;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C4;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}")
        self.tab_second_lvl.setDocumentMode(True)
        self.tab_second_lvl.setObjectName("tab_second_lvl")
        self.tab_entry_results = QtWidgets.QWidget()
        self.tab_entry_results.setObjectName("tab_entry_results")
        self.tab_second_lvl.addTab(self.tab_entry_results, "")
        self.tab_entry_heat = QtWidgets.QWidget()
        self.tab_entry_heat.setObjectName("tab_entry_heat")
        self.tab_second_lvl.addTab(self.tab_entry_heat, "")
        self.tab_entry_break = QtWidgets.QWidget()
        self.tab_entry_break.setObjectName("tab_entry_break")
        self.gb_addbreak_location = QtWidgets.QGroupBox(self.tab_entry_break)
        self.gb_addbreak_location.setGeometry(QtCore.QRect(49, 39, 461, 291))
        self.gb_addbreak_location.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 75 14pt \"Verdana\";\n"
"")
        self.gb_addbreak_location.setObjectName("gb_addbreak_location")
        self.pb_addbreak_newloc = QtWidgets.QPushButton(self.gb_addbreak_location)
        self.pb_addbreak_newloc.setEnabled(True)
        self.pb_addbreak_newloc.setGeometry(QtCore.QRect(140, 220, 151, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_addbreak_newloc.sizePolicy().hasHeightForWidth())
        self.pb_addbreak_newloc.setSizePolicy(sizePolicy)
        self.pb_addbreak_newloc.setMinimumSize(QtCore.QSize(151, 50))
        self.pb_addbreak_newloc.setStyleSheet("background-color: rgb(246, 234, 190);\n"
"font: 63 11pt \"Verdana\";")
        self.pb_addbreak_newloc.setObjectName("pb_addbreak_newloc")
        self.formLayoutWidget = QtWidgets.QWidget(self.gb_addbreak_location)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 50, 371, 153))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.flayout_addbreak_location = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.flayout_addbreak_location.setContentsMargins(0, 0, 0, 0)
        self.flayout_addbreak_location.setObjectName("flayout_addbreak_location")
        self.label_addbreak_continent = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_addbreak_continent.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_addbreak_continent.setObjectName("label_addbreak_continent")
        self.flayout_addbreak_location.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_addbreak_continent)
        self.label_addbreak_country = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_addbreak_country.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_addbreak_country.setObjectName("label_addbreak_country")
        self.flayout_addbreak_location.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_addbreak_country)
        self.cb_addbreak_country = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_addbreak_country.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.cb_addbreak_country.setObjectName("cb_addbreak_country")
        self.flayout_addbreak_location.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_addbreak_country)
        self.label_addbreak_region = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_addbreak_region.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_addbreak_region.setObjectName("label_addbreak_region")
        self.flayout_addbreak_location.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_addbreak_region)
        self.cb_addbreak_region = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_addbreak_region.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.cb_addbreak_region.setObjectName("cb_addbreak_region")
        self.flayout_addbreak_location.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_addbreak_region)
        self.label_addbreak_break = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_addbreak_break.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_addbreak_break.setObjectName("label_addbreak_break")
        self.flayout_addbreak_location.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_addbreak_break)
        self.line_addbreak_break = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_addbreak_break.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.line_addbreak_break.setObjectName("line_addbreak_break")
        self.flayout_addbreak_location.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_addbreak_break)
        self.cb_addbreak_continent = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_addbreak_continent.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.cb_addbreak_continent.setObjectName("cb_addbreak_continent")
        self.flayout_addbreak_location.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_addbreak_continent)
        self.gb_addbreak_surfability = QtWidgets.QGroupBox(self.tab_entry_break)
        self.gb_addbreak_surfability.setGeometry(QtCore.QRect(590, 380, 261, 231))
        self.gb_addbreak_surfability.setStyleSheet("background-color: rgb(185, 131, 255);\n"
"font: 75 14pt \"Verdana\";\n"
"")
        self.gb_addbreak_surfability.setObjectName("gb_addbreak_surfability")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.gb_addbreak_surfability)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 57, 192, 141))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.flayout_addbreak_surfability = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.flayout_addbreak_surfability.setContentsMargins(0, 0, 0, 0)
        self.flayout_addbreak_surfability.setObjectName("flayout_addbreak_surfability")
        self.label_addbreak_clean = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_addbreak_clean.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_addbreak_clean.setObjectName("label_addbreak_clean")
        self.flayout_addbreak_surfability.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_addbreak_clean)
        self.label_addbreak_small = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_addbreak_small.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_addbreak_small.setObjectName("label_addbreak_small")
        self.flayout_addbreak_surfability.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_addbreak_small)
        self.label_addbreak_blown = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_addbreak_blown.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_addbreak_blown.setObjectName("label_addbreak_blown")
        self.flayout_addbreak_surfability.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_addbreak_blown)
        self.line_addbreak_clean = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_addbreak_clean.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.line_addbreak_clean.setObjectName("line_addbreak_clean")
        self.flayout_addbreak_surfability.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_addbreak_clean)
        self.line_addbreak_blown = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_addbreak_blown.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.line_addbreak_blown.setObjectName("line_addbreak_blown")
        self.flayout_addbreak_surfability.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_addbreak_blown)
        self.line_addbreak_small = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.line_addbreak_small.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.line_addbreak_small.setObjectName("line_addbreak_small")
        self.flayout_addbreak_surfability.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_addbreak_small)
        self.gb_addbreak_type = QtWidgets.QGroupBox(self.tab_entry_break)
        self.gb_addbreak_type.setGeometry(QtCore.QRect(590, 40, 461, 291))
        self.gb_addbreak_type.setStyleSheet("background-color: rgb(185, 131, 255);\n"
"font: 75 14pt \"Verdana\";\n"
"")
        self.gb_addbreak_type.setObjectName("gb_addbreak_type")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.gb_addbreak_type)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(49, 59, 341, 191))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.flayout_addbreak_type = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.flayout_addbreak_type.setContentsMargins(0, 0, 0, 0)
        self.flayout_addbreak_type.setObjectName("flayout_addbreak_type")
        self.check_addbreak_beach = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.check_addbreak_beach.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.check_addbreak_beach.setObjectName("check_addbreak_beach")
        self.flayout_addbreak_type.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.check_addbreak_beach)
        self.check_addbreak_point = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.check_addbreak_point.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.check_addbreak_point.setObjectName("check_addbreak_point")
        self.flayout_addbreak_type.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.check_addbreak_point)
        self.check_addbreak_reef = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.check_addbreak_reef.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.check_addbreak_reef.setObjectName("check_addbreak_reef")
        self.flayout_addbreak_type.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.check_addbreak_reef)
        self.check_addbreak_river = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.check_addbreak_river.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.check_addbreak_river.setObjectName("check_addbreak_river")
        self.flayout_addbreak_type.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.check_addbreak_river)
        self.check_addbreak_sandbar = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.check_addbreak_sandbar.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.check_addbreak_sandbar.setObjectName("check_addbreak_sandbar")
        self.flayout_addbreak_type.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.check_addbreak_sandbar)
        self.check_addbreak_jetty = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.check_addbreak_jetty.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.check_addbreak_jetty.setObjectName("check_addbreak_jetty")
        self.flayout_addbreak_type.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.check_addbreak_jetty)
        self.check_addbreak_eng = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.check_addbreak_eng.setStyleSheet("font: 63 12pt \"Cascadia Mono SemiBold\";")
        self.check_addbreak_eng.setObjectName("check_addbreak_eng")
        self.flayout_addbreak_type.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.check_addbreak_eng)
        self.gb_addbreak_skill = QtWidgets.QGroupBox(self.tab_entry_break)
        self.gb_addbreak_skill.setGeometry(QtCore.QRect(50, 380, 461, 231))
        self.gb_addbreak_skill.setStyleSheet("background-color: rgb(254, 131, 198);\n"
"font: 75 14pt \"Verdana\";")
        self.gb_addbreak_skill.setObjectName("gb_addbreak_skill")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.gb_addbreak_skill)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(30, 50, 412, 161))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.flayout_addbreak_skill = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.flayout_addbreak_skill.setContentsMargins(0, 0, 0, 0)
        self.flayout_addbreak_skill.setObjectName("flayout_addbreak_skill")
        self.label_addbreak_reliability = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_addbreak_reliability.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_addbreak_reliability.setObjectName("label_addbreak_reliability")
        self.flayout_addbreak_skill.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_addbreak_reliability)
        self.label_addbreak_ability = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_addbreak_ability.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_addbreak_ability.setObjectName("label_addbreak_ability")
        self.flayout_addbreak_skill.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_addbreak_ability)
        self.hlayout_addbreak_ability = QtWidgets.QHBoxLayout()
        self.hlayout_addbreak_ability.setObjectName("hlayout_addbreak_ability")
        self.check_addbreak_ability_green = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_addbreak_ability_green.sizePolicy().hasHeightForWidth())
        self.check_addbreak_ability_green.setSizePolicy(sizePolicy)
        self.check_addbreak_ability_green.setMinimumSize(QtCore.QSize(75, 0))
        self.check_addbreak_ability_green.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: rgb(40, 223, 153);")
        self.check_addbreak_ability_green.setObjectName("check_addbreak_ability_green")
        self.hlayout_addbreak_ability.addWidget(self.check_addbreak_ability_green)
        self.check_addbreak_ability_yellow = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_addbreak_ability_yellow.sizePolicy().hasHeightForWidth())
        self.check_addbreak_ability_yellow.setSizePolicy(sizePolicy)
        self.check_addbreak_ability_yellow.setMinimumSize(QtCore.QSize(75, 0))
        self.check_addbreak_ability_yellow.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: #FDFFA9;")
        self.check_addbreak_ability_yellow.setObjectName("check_addbreak_ability_yellow")
        self.hlayout_addbreak_ability.addWidget(self.check_addbreak_ability_yellow)
        self.check_addbreak_ability_red = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_addbreak_ability_red.sizePolicy().hasHeightForWidth())
        self.check_addbreak_ability_red.setSizePolicy(sizePolicy)
        self.check_addbreak_ability_red.setMinimumSize(QtCore.QSize(75, 0))
        self.check_addbreak_ability_red.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: rgb(216, 58, 86);")
        self.check_addbreak_ability_red.setObjectName("check_addbreak_ability_red")
        self.hlayout_addbreak_ability.addWidget(self.check_addbreak_ability_red)
        self.flayout_addbreak_skill.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.hlayout_addbreak_ability)
        self.label_addbreak_burn = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_addbreak_burn.setStyleSheet("font: 63 10pt \"Cascadia Mono SemiBold\";")
        self.label_addbreak_burn.setObjectName("label_addbreak_burn")
        self.flayout_addbreak_skill.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_addbreak_burn)
        self.halyout_addbreak_burn = QtWidgets.QHBoxLayout()
        self.halyout_addbreak_burn.setObjectName("halyout_addbreak_burn")
        self.check_addbreak_burn_green = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_addbreak_burn_green.sizePolicy().hasHeightForWidth())
        self.check_addbreak_burn_green.setSizePolicy(sizePolicy)
        self.check_addbreak_burn_green.setMinimumSize(QtCore.QSize(75, 0))
        self.check_addbreak_burn_green.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: rgb(40, 223, 153);")
        self.check_addbreak_burn_green.setObjectName("check_addbreak_burn_green")
        self.halyout_addbreak_burn.addWidget(self.check_addbreak_burn_green)
        self.check_addbreak_burn_yellow = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_addbreak_burn_yellow.sizePolicy().hasHeightForWidth())
        self.check_addbreak_burn_yellow.setSizePolicy(sizePolicy)
        self.check_addbreak_burn_yellow.setMinimumSize(QtCore.QSize(75, 0))
        self.check_addbreak_burn_yellow.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: #FDFFA9;")
        self.check_addbreak_burn_yellow.setObjectName("check_addbreak_burn_yellow")
        self.halyout_addbreak_burn.addWidget(self.check_addbreak_burn_yellow)
        self.check_addbreak_burn_red = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_addbreak_burn_red.sizePolicy().hasHeightForWidth())
        self.check_addbreak_burn_red.setSizePolicy(sizePolicy)
        self.check_addbreak_burn_red.setMinimumSize(QtCore.QSize(75, 0))
        self.check_addbreak_burn_red.setStyleSheet("font: 24pt \"Wingdings\";\n"
"color: rgb(216, 58, 86);")
        self.check_addbreak_burn_red.setObjectName("check_addbreak_burn_red")
        self.halyout_addbreak_burn.addWidget(self.check_addbreak_burn_red)
        self.flayout_addbreak_skill.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.halyout_addbreak_burn)
        self.cb_addbreak_reliability = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cb_addbreak_reliability.setStyleSheet("background-color: rgb(251, 248, 241);")
        self.cb_addbreak_reliability.setObjectName("cb_addbreak_reliability")
        self.cb_addbreak_reliability.addItem("")
        self.cb_addbreak_reliability.addItem("")
        self.cb_addbreak_reliability.addItem("")
        self.cb_addbreak_reliability.addItem("")
        self.cb_addbreak_reliability.addItem("")
        self.flayout_addbreak_skill.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_addbreak_reliability)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.flayout_addbreak_skill.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.pb_addbreak_submit = QtWidgets.QPushButton(self.tab_entry_break)
        self.pb_addbreak_submit.setEnabled(True)
        self.pb_addbreak_submit.setGeometry(QtCore.QRect(890, 530, 151, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_addbreak_submit.sizePolicy().hasHeightForWidth())
        self.pb_addbreak_submit.setSizePolicy(sizePolicy)
        self.pb_addbreak_submit.setMinimumSize(QtCore.QSize(151, 50))
        self.pb_addbreak_submit.setStyleSheet("background-color: rgb(154, 223, 244);\n"
"font: 63 11pt \"Verdana\";")
        self.pb_addbreak_submit.setObjectName("pb_addbreak_submit")
        self.pb_addbreak_clear = QtWidgets.QPushButton(self.tab_entry_break)
        self.pb_addbreak_clear.setEnabled(True)
        self.pb_addbreak_clear.setGeometry(QtCore.QRect(890, 420, 151, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_addbreak_clear.sizePolicy().hasHeightForWidth())
        self.pb_addbreak_clear.setSizePolicy(sizePolicy)
        self.pb_addbreak_clear.setMinimumSize(QtCore.QSize(151, 50))
        self.pb_addbreak_clear.setStyleSheet("background-color: rgb(154, 223, 244);\n"
"font: 63 11pt \"Verdana\";")
        self.pb_addbreak_clear.setObjectName("pb_addbreak_clear")
        self.tab_second_lvl.addTab(self.tab_entry_break, "")
        self.tab_entry_surfer = QtWidgets.QWidget()
        self.tab_entry_surfer.setObjectName("tab_entry_surfer")
        self.tab_second_lvl.addTab(self.tab_entry_surfer, "")
        self.tab_top_lvl.addTab(self.tab_data_entry, "")

        self.retranslateUi(Form)
        self.tab_top_lvl.setCurrentIndex(3)
        self.tab_second_lvl.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tab_top_lvl.setTabText(self.tab_top_lvl.indexOf(self.tab_main), _translate("Form", "Main"))
        self.tab_top_lvl.setTabText(self.tab_top_lvl.indexOf(self.tab_schedule), _translate("Form", "Schedule"))
        self.tab_top_lvl.setTabText(self.tab_top_lvl.indexOf(self.tab_heat_analysis), _translate("Form", "Heat Analysis"))
        self.tab_second_lvl.setTabText(self.tab_second_lvl.indexOf(self.tab_entry_results), _translate("Form", "Heat Resuts"))
        self.tab_second_lvl.setTabText(self.tab_second_lvl.indexOf(self.tab_entry_heat), _translate("Form", "Add Heat"))
        self.gb_addbreak_location.setTitle(_translate("Form", "Location"))
        self.pb_addbreak_newloc.setText(_translate("Form", "New Location"))
        self.label_addbreak_continent.setText(_translate("Form", "Continent:"))
        self.label_addbreak_country.setText(_translate("Form", "Country:"))
        self.label_addbreak_region.setText(_translate("Form", "Region:"))
        self.label_addbreak_break.setText(_translate("Form", "Break:"))
        self.gb_addbreak_surfability.setTitle(_translate("Form", "Surfability (%)"))
        self.label_addbreak_clean.setText(_translate("Form", "Clean:"))
        self.label_addbreak_small.setText(_translate("Form", "Too Small:"))
        self.label_addbreak_blown.setText(_translate("Form", "Blown Out:"))
        self.gb_addbreak_type.setTitle(_translate("Form", "Break Type"))
        self.check_addbreak_beach.setText(_translate("Form", "Beach"))
        self.check_addbreak_point.setText(_translate("Form", "Point"))
        self.check_addbreak_reef.setText(_translate("Form", "Reef"))
        self.check_addbreak_river.setText(_translate("Form", "River"))
        self.check_addbreak_sandbar.setText(_translate("Form", "Sandbar"))
        self.check_addbreak_jetty.setText(_translate("Form", "Jetty"))
        self.check_addbreak_eng.setText(_translate("Form", "Engineered   "))
        self.gb_addbreak_skill.setTitle(_translate("Form", "Skill Factors"))
        self.label_addbreak_reliability.setText(_translate("Form", "Reliability:"))
        self.label_addbreak_ability.setText(_translate("Form", "Ability:"))
        self.check_addbreak_ability_green.setText(_translate("Form", "l"))
        self.check_addbreak_ability_yellow.setText(_translate("Form", "l"))
        self.check_addbreak_ability_red.setText(_translate("Form", "l"))
        self.label_addbreak_burn.setText(_translate("Form", "Shoulder Burn:  "))
        self.check_addbreak_burn_green.setText(_translate("Form", "l"))
        self.check_addbreak_burn_yellow.setText(_translate("Form", "l"))
        self.check_addbreak_burn_red.setText(_translate("Form", "l"))
        self.cb_addbreak_reliability.setItemText(0, _translate("Form", "Very Consistent"))
        self.cb_addbreak_reliability.setItemText(1, _translate("Form", "Consistent"))
        self.cb_addbreak_reliability.setItemText(2, _translate("Form", "Variable"))
        self.cb_addbreak_reliability.setItemText(3, _translate("Form", "Inconsistent"))
        self.cb_addbreak_reliability.setItemText(4, _translate("Form", "Very Inconsistent"))
        self.pb_addbreak_submit.setText(_translate("Form", "Submit"))
        self.pb_addbreak_clear.setText(_translate("Form", "Clear"))
        self.tab_second_lvl.setTabText(self.tab_second_lvl.indexOf(self.tab_entry_break), _translate("Form", "Add Break"))
        self.tab_second_lvl.setTabText(self.tab_second_lvl.indexOf(self.tab_entry_surfer), _translate("Form", "Add Surfer"))
        self.tab_top_lvl.setTabText(self.tab_top_lvl.indexOf(self.tab_data_entry), _translate("Form", "Data Entry"))
